from enum import Enum


class TaskType(Enum):
    CREATE_FILE = "CREATE_FILE"
    WRITE_FILE = "WRITE_FILE"
    DELETE_FILE = "DELETE_FILE"

    CREATE_DIRECTORY = "CREATE_DIRECTORY"
    DELETE_DIRECTORY = "DELETE_DIRECTORY"

    OPEN_APPLICATION = "OPEN_APPLICATION"
    CLOSE_APPLICATION = "CLOSE_APPLICATION"

    SEND_NETWORK_REQUEST = "SEND_NETWORK_REQUEST"
    RECEIVE_NETWORK_RESOURCE = "RECEIVE_NETWORK_RESOURCE"
